try :
    print(x)

except :
    print("An error has occurred")

finally:
    print("Success")



num1 = 20
num2 = 0
print(num1/num2)

try :
    num1 = 20
    num2 = 0
    print(num1 / num2)
except :
    print("An error has occurred")
